server:
  port: 8080
  servlet:
    context-path: /community

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3
  devtools:
    livereload:
      port: 35730
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #  配置邮箱
  mail:
    host: smtp.qq.com
    port: 465
    username: 260602448@qq.com
    password: mpdckdwkmxyvbjba
    protocol: smtps
  #RedisProperties
  redis:
    database: 11
    host: localhost
    port: 6379
  #KafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      # consumer偏移量记录下来提交
      enable-auto-commit: true
      # 自动提交频率
      auto-commit-interval: 3000
  #ElasticsearchPropertier--Springboot版本2.1.5 9300:TCP通信
  data:
    elasticsearch:
      cluster-name: demonowcoder
      cluster-nodes: 127.0.0.1:9300


mybatis:
  type-aliases-package: com.xmy.demonowcoder.entities
  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置
  configuration:
    #  驼峰命名（可以不写全局；配置文件，所有全局配置文件的配置都放在configuration配置项中即可）
    map-underscore-to-camel-case: true
    use-generated-keys: true #主键自增
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#community域名
community:
  path:
    domain: http://localhost:8080
    upload: d:/DemoNowcoder/upload

